language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install ."
  - "pip install coveralls"
script:
  - cd wsgi
  - coverage run --source=etwente,presentations manage.py test
after_success:
  - coveralls
